version: '3'
services:
  backend:
    image: aniket036/flaskapp:latest
    ports:
      -  "5000:5000"
    environment:
       MYSQL_HOST: "mysql"
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: "admin"
       MYSQL_DB: "myDb"
    depends_on:
      - mysql
    networks: "twotier"

  mysql:
    image: mysql:5.7
    environment:
       MYSQL_DATABASE: "myDb"
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: "admin"
       MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    networks: "twotier"

    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql-data:/var/lib/mysql
volumes:
   mysql-data:
networks:
  twotier:
